server:
  port: 1000

spring:
  data:
    redis:
      host: 192.168.2.100
      port: 6379
      database: 0
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.100:8848
    gateway:
      discovery:
        locator:
          enabled: true   # 动态路由，从注册中心根据微服务的名称获得目标节点的地址
      routes:
        - id: authRoute
          uri: lb://auth-service
          predicates:
            - Path=/a/**,/passport/**
        - id: fileRoute
          uri: lb://file-service
          predicates:
            - Path=/f/**,/file/**,/static/**
        - id: mainRoute
          uri: lb://main-service
          predicates:
            - Path=/m/**,/userinfo/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true
