server:
  port: 55

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.100:8848

minio:
  endpoint: http://192.168.2.100:9000
  fileHost: http://192.168.2.100:9000
  bucketName: mychat
  accessKey: yky
  secretKey: yky123456