server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # 不限制请求体大小

spring:
  application:
    name: main-service
  profiles:
    active: dev

# 日志级别
logging:
  level:
    root: info

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.yky.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn