server:
  port: 88

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.100:3306/mychat?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 18000000
      connection-test-query: SELECT 1
  data:
    redis:
      host: 192.168.2.100
      port: 6379
      database: 0
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.100:8848